// [WARNING] This file is generated by running `$ qore codegen` on your root project, please do not edit

/// <reference types="@feedloop/qore-client" />
import { QoreSchema } from "@feedloop/qore-client";

declare module "@feedloop/qore-client" {
  type BlogsTableRow = {
    id: string;
    name: string;
    description: string;
    img: string;
    title: string;
    createdAt: Date;
    updatedAt: Date;
  };

  type MemberTableRow = {
    id: string;
    email: string;
    role: { id: string; displayField: string };
  };

  type BudgetsTableRow = {
    id: string;
    item: string;
    price: number;
    amount: number;
    type: "income" | "expense";
  };

  type AllBlogsViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
      img: string;
      title: string;
      createdAt: Date;
      updatedAt: Date;
    };
    write: {
      name: string;
      description: string;
      img: string;
      title: string;
      createdAt: Date;
      updatedAt: Date;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllMemberViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
    };
    write: {
      email: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllBudgetsViewRow = {
    read: {
      id: string;
      item: string;
      price: number;
      amount: number;
      type: "income" | "expense";
    };
    write: {
      item: string;
      price: number;
      amount: number;
      type: "income" | "expense";
    };
    params: {};
    actions: {};
    forms: {};
  };

  type ProjectSchema = {
    allBlogs: AllBlogsViewRow;
    allMember: AllMemberViewRow;
    allBudgets: AllBudgetsViewRow;
  };
}
